# Generated by Django 4.1.12 on 2023-12-11 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RacaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=50, verbose_name='raça')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_animal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_animal', models.ImageField(upload_to='img_animal/', verbose_name='imagem do animal')),
                ('titulo', models.CharField(max_length=200)),
                ('nome_animal', models.CharField(default='Sem nome', max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('N', 'Não especificado')], max_length=1, verbose_name='sexo')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('observacao', models.TextField(default='sem observações')),
                ('destaque', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.tipoanimal', verbose_name='Animal')),
                ('raca', models.ForeignKey(default='SRD (Sem Raça Definida)', on_delete=django.db.models.deletion.CASCADE, to='animais.racaanimal', verbose_name='raça')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
