# Generated by Django 4.1.12 on 2023-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
