# Generated by Django 4.1.12 on 2023-12-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='favoritado',
            field=models.BooleanField(default=False),
        ),
    ]
