# Generated by Django 4.1.12 on 2023-12-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_remove_animal_favoritado_alter_animal_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='favoritado',
            field=models.BooleanField(default=False),
        ),
    ]
