# Generated by Django 4.1.12 on 2023-12-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_animal_favoritado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animais.tipoanimal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(default='SRD (Sem Raça Definida)', on_delete=django.db.models.deletion.PROTECT, to='animais.racaanimal', verbose_name='raça'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('N', 'Não especificado')], max_length=1, verbose_name='sexo'),
        ),
    ]
